# 'bundle exec jekyll serve' 명령을 실행해도 자동으로 로드되지 않습니다.
# 이 파일을 변경하는 경우 서버 프로세스를 다시 시작하십시오.
# YAML 구문 참고:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: MyCoding
author: dlehdgh
email: dlehdgh2@naver.com
description: >-
  이 블로그는 내가 공부했던 내용을 체계적으로 정리하여 나중에 쉽게 찾아볼 수 있도록 하는 공간입니다.
  주로 프로그래밍 언어에 관한 글을 올릴 예정입니다.

baseurl: "" # 사이트의 하위 경로, e.g. /blog
url: "https://dlehdgh.github.io" # 사이트의 기본 호스트 이름 및 프로토콜, e.g. http://example.com
permalink: /:categories/:title/ # 포스트 주소 e.g. /:categories/:year/:month/:day/:title:output_ext

# 포스트 날짜가 UTC 날짜 보다 미래인 경우에도 허용
future: true

# 날짜 형식 지정(년.월.일 시:분:초 AM/PM)
date_format: "%Y-%m-%d"
date_time_format: "%Y-%m-%d %I:%M"

# Github Utterances 댓글 설정
utterances:
  repo: dlehdgh/mycoding # 댓글을 추가할 저장소
  issue-term: pathname # 댓글 추가 시 issue의 제목 유형
  theme: github-dark-orange # 댓글 테마

# Generate social links
social_links:
    - { platform: github,         user_url: "https://github.com/dlehdgh/dlehdgh.github.io" }
  #  - { platform: devto,          user_url: "https://dev.to/jekyll" }
  #  - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
  #  - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
  #  - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
  #  - { platform: gitlab,         user_url: "https://gitlab.com/jekyll" }
  #  - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
  #  - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
  #  - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
  #  - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jekyll" }
  #  - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
  #  - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
  #  - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
  #  - { platform: telegram,       user_url: "https://t.me/jekyll" }
  #  - { platform: twitter,        user_url: "https://twitter.com/jekyllrb" }
  #  - { platform: x,              user_url: "https://x.com/jekyllrb" }
  #  - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }

# Build settings
# theme: minima

# 마크다운 설정
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# 페이지 나누기 설정
paginate: 10
paginate_path: "/posts/page:num/"
paginate_size: 5

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Tipue Search 환경설정
tipue_search:
  include:
    pages: false
    collections: []
  exclude:
    files: [search.html, index.html, 404.html, categories/index.md, tags.md, year-archive.md, testing.md]
    categories: []
    tags: []


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
